language: python
python:
  - "3.8"
services:
  - docker
env:
  global:
    - QUAY_REPO="quay.io/opentargets/platform-input-support"
install:
  # build docker image
  - docker build --pull --cache-from "${QUAY_REPO}:${TRAVIS_BRANCH}" --tag "${QUAY_REPO}" .
script:
   - docker run -it --entrypoint poetry "${QUAY_REPO}" run python3.8 -m pytest --cov=modules --cov-report term tests/ --fulltrace
after_success:
  - codecov
  - |
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then
      echo "--- Building and pushing Docker image ---"
      docker login -u="${QUAY_USER}" -p="${QUAY_PASSWORD}" quay.io
      git_sha="${TRAVIS_COMMIT}"
      docker tag "${QUAY_REPO}" "${QUAY_REPO}:${TRAVIS_BRANCH}"
      docker tag "${QUAY_REPO}" "${QUAY_REPO}:${git_sha}-${TRAVIS_BRANCH}"
      docker push "${QUAY_REPO}:${TRAVIS_BRANCH}" && docker push "${QUAY_REPO}:${git_sha}-${TRAVIS_BRANCH}"
      if [ "${TRAVIS_TAG}" != "" ]; then
        echo "Pushing tagged released container ${TRAVIS_TAG}"
        docker tag "${QUAY_REPO}:${TRAVIS_BRANCH}" "${QUAY_REPO}:${TRAVIS_TAG}"
        docker push "${QUAY_REPO}:${TRAVIS_TAG}"
      fi
      if [ "${TRAVIS_BRANCH}" = "master" ]; then
        echo "This is the Master branch, pushing as latest"
        docker tag "${QUAY_REPO}:${TRAVIS_BRANCH}" "${QUAY_REPO}:latest"
        docker push "${QUAY_REPO}:latest"
      fi
    fi
