name: pis-py3
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - addict=2.3.0=py38h32f6830_2
  - async-timeout=3.0.1=py38_0
  - attrs=20.2.0=py_0
  - blas=1.0=mkl
  - cachetools=4.1.1=py_0
  - chardet=3.0.4=py38_1003
  - configargparse=1.2.3=py_0
  - elasticsearch=6.3.1=py_0
  - elasticsearch-dsl=7.3.0=py38_0
  - google-api-core=1.22.2=py38_0
  - google-auth=1.22.1=py_0
  - google-cloud-core=1.4.3=py_0
  - google-cloud-storage=1.32.0=py_0
  - google-resumable-media=1.1.0=py_1
  - googleapis-common-protos=1.52.0=py38_0
  - idna=2.10=py_0
  - iniconfig=1.1.1=pyh9f0ad1d_0
  - jsonlines=2.0.0=pyhd3deb0d_0
  - mock=4.0.2=py_0
  - more-itertools=8.6.0=pyhd8ed1ab_0
  - packaging=20.8=pyhd3deb0d_0
  - pip=20.2.4=py38_0
  - py=1.10.0=pyhd3deb0d_0
  - py4j=0.10.9=py_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.8=py_0
  - pytest-cov=2.10.1=py_0
  - pycparser=2.20=py_2
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pysocks=1.7.1=py38_0
  - pyspark=3.0.0=py_0
  - pytest=6.1.1=py38_0
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytz=2020.1=py_0
  - requests=2.24.0=py_0
  - rsa=4.6=py_0
  - six=1.15.0=py_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tqdm=4.50.2=py_0
  - urllib3=1.25.11=py_0
  - wheel=0.35.1=py_0
  - pip:
    - future==0.18.2
    - inflection==0.5.1
    - jsonschema==3.2.0
    - markdown==3.3.3
    - opentargets-urlzsource==1.0.0
    - pyrsistent==0.17.3
    - python-jsonschema-objects==0.3.13
    - requests-file==1.5.1
    - certifi==2020.12.5
    - yarl==1.5.1
    - brotli==1.0.9
    - mysqlclient==2.0.1
    - libcrc32c==1.1.1
    - setuptools==50.3.0
    - mkl_fft==1.2.0
    - multidict==4.7.6
    - libgcc-ng==9.1.0
    - sqlalchemy==1.3.19
    - pandas==1.1.3
    - numpy==1.19.1
    - mkl==2020.2
    - tk==8.6.10
    - zstd==1.3.7
    - libffi==3.3
    - double-conversion==3.1.5
    - xz==5.2.5
    - mkl-service==2.3.0
    - aiohttp==3.6.3
    - libboost==1.71.0
    - ld_impl_linux-64==2.33.1
    - readline==8.0
    - pyyaml==5.3.1
    - mysql-connector-c==6.1.11
    - libstdcxx-ng==9.1.0
    - thrift-cpp==0.11.0
    - zlib==1.2.11
    - boost-cpp==1.71.0
    - psutil==5.7.2
    - re2==2019.08.01
    - coverage==5.3
    - simplejson==3.17.2
    - libevent==2.1.8
    - snappy==1.1.8
    - pluggy==0.13.1
    - pyarrow==0.15.1
    - libedit==3.1.20191231
    - libprotobuf==3.11.2
    - google-crc32c==1.0.0
    - cffi==1.14.3
    - openssl==1.1.1h
    - glog==0.4.0
    - brotlipy==0.7.0
    - python==3.8.5
    - sqlite==3.33.0
    - ncurses==6.2
    - lz4-c==1.8.1.2
    - numpy-base==1.19.1
    - uriparser==0.9.3
    - gflags==2.2.2
    - cryptography==3.1.1
    - arrow-cpp==0.15.1
    - bzip2==1.0.8
    - protobuf==3.11.2
    - c-ares==1.16.1
    - yaml==0.2.5
    - grpc-cpp==1.26.0
    - mkl_random==1.1.1
    - intel-openmp==2020.2
    - icu==58.2
    - ca-certificates==2020.12.5
