name: otpis
channels:
  - conda-forge
  - defaults
dependencies:
  - addict
  - configargparse
  - elasticsearch==7.17.0
  - elasticsearch-dsl
  - jsonlines
  - google-cloud-storage=1.42.3
  - gspread
  - mock
  - pip
  - python=3.8.8
  - pytest
  - pytest-cov
  - pyyaml
  - yapsy
  - tqdm
  - jsonpickle
  - munch
  - pip:
      - future==0.18.2
      - opentargets-urlzsource==1.0.0
      - requests-file==1.5.1
      - StrEnum
